[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.5.4",
    "aiohttp>=3.12.0",
    "azure-ai-inference>=1.0.0b9",
]
